Name:		texlive-collection-fontsextra
Epoch:		1
Version:	64952
Release:	1
Summary:	Additional fonts
Group:		Publishing
URL:		http://tug.org/texlive
License:	http://www.tug.org/texlive/LICENSE.TL
Source0:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/collection-fontsextra.r64952.tar.xz
BuildArch:	noarch
BuildRequires:	texlive-tlpkg
Requires(pre):	texlive-tlpkg
Requires:	texlive-collection-basic
Requires:	texlive-Asana-Math
Requires:	texlive-accanthis
Requires:	texlive-adforn
Requires:	texlive-adfsymbols
Requires:	texlive-aecc
Requires:	texlive-alegreya
Requires:	texlive-allrunes
Requires:	texlive-anonymouspro
Requires:	texlive-antiqua
Requires:	texlive-antt
Requires:	texlive-archaic
Requires:	texlive-arev
Requires:	texlive-ascii-font
Requires:	texlive-aspectratio
Requires:	texlive-astro
Requires:	texlive-augie
Requires:	texlive-auncial-new
Requires:	texlive-aurical
Requires:	texlive-b1encoding
Requires:	texlive-barcodes
Requires:	texlive-baskervald
Requires:	texlive-baskervaldx
Requires:	texlive-bbding
Requires:	texlive-bbm
Requires:	texlive-bbm-macros
Requires:	texlive-bbold
Requires:	texlive-bbold-type1
Requires:	texlive-belleek
Requires:	texlive-bera
Requires:	texlive-berenisadf
Requires:	texlive-bguq
Requires:	texlive-blacklettert1
Requires:	texlive-boisik
Requires:	texlive-bookhands
Requires:	texlive-boondox
Requires:	texlive-braille
Requires:	texlive-brushscr
Requires:	texlive-cabin
Requires:	texlive-calligra
Requires:	texlive-calligra-type1
Requires:	texlive-cantarell
Requires:	texlive-carolmin-ps
Requires:	texlive-ccicons
Requires:	texlive-cfr-lm
Requires:	texlive-cherokee
Requires:	texlive-cinzel
Requires:	texlive-clearsans
Requires:	texlive-cm-lgc
Requires:	texlive-cm-unicode
Requires:	texlive-cmbright
Requires:	texlive-cmll
Requires:	texlive-cmpica
Requires:	texlive-cmtiup
Requires:	texlive-comfortaa
Requires:	texlive-concmath-fonts
Requires:	texlive-cookingsymbols
Requires:	texlive-countriesofeurope
Requires:	texlive-courier-scaled
Requires:	texlive-cryst
Requires:	texlive-cyklop
Requires:	texlive-dancers
Requires:	texlive-dejavu
Requires:	texlive-dice
Requires:	texlive-dictsym
Requires:	texlive-dingbat
Requires:	texlive-doublestroke
Requires:	texlive-dozenal
Requires:	texlive-droid
Requires:	texlive-duerer
Requires:	texlive-duerer-latex
Requires:	texlive-dutchcal
Requires:	texlive-ean
Requires:	texlive-ebgaramond
Requires:	texlive-ecc
Requires:	texlive-eco
Requires:	texlive-eiad
Requires:	texlive-eiad-ltx
Requires:	texlive-electrum
Requires:	texlive-elvish
Requires:	texlive-epigrafica
Requires:	texlive-epsdice
Requires:	texlive-esstix
Requires:	texlive-esvect
Requires:	texlive-eulervm
Requires:	texlive-euxm
Requires:	texlive-fbb
Requires:	texlive-fdsymbol
Requires:	texlive-fetamont
Requires:	texlive-feyn
Requires:	texlive-fge
Requires:	texlive-fira
Requires:	texlive-foekfont
Requires:	texlive-fonetika
Requires:	texlive-fontawesome
Requires:	texlive-fourier
Requires:	texlive-fouriernc
Requires:	texlive-frcursive
Requires:	texlive-genealogy
Requires:	texlive-gentium-tug
Requires:	texlive-gfsartemisia
Requires:	texlive-gfsbodoni
Requires:	texlive-gfscomplutum
Requires:	texlive-gfsdidot
Requires:	texlive-gfsneohellenic
Requires:	texlive-gfssolomos
Requires:	texlive-gillcm
Requires:	texlive-gillius
Requires:	texlive-gnu-freefont
Requires:	texlive-gothic
Requires:	texlive-greenpoint
Requires:	texlive-grotesq
Requires:	texlive-hacm
Requires:	texlive-hands
Requires:	texlive-heuristica
Requires:	texlive-hfbright
Requires:	texlive-hfoldsty
Requires:	texlive-ifsym
Requires:	texlive-inconsolata
Requires:	texlive-initials
Requires:	texlive-ipaex-type1
Requires:	texlive-iwona
Requires:	texlive-jablantile
Requires:	texlive-jamtimes
Requires:	texlive-junicode
Requires:	texlive-kixfont
Requires:	texlive-knuthotherfonts
Requires:	texlive-kpfonts
Requires:	texlive-kurier
Requires:	texlive-lato
Requires:	texlive-lfb
Requires:	texlive-libertine
Requires:	texlive-librebaskerville
Requires:	texlive-librecaslon
Requires:	texlive-libris
Requires:	texlive-linearA
Requires:	texlive-lobster2
Requires:	texlive-lxfonts
Requires:	texlive-ly1
Requires:	texlive-mathabx
Requires:	texlive-mathabx-type1
Requires:	texlive-mathdesign
Requires:	texlive-mdputu
Requires:	texlive-mdsymbol
Requires:	texlive-merriweather
Requires:	texlive-mintspirit
Requires:	texlive-mnsymbol
Requires:	texlive-newpx
Requires:	texlive-newtx
Requires:	texlive-newtxtt
Requires:	texlive-nkarta
Requires:	texlive-obnov
Requires:	texlive-ocherokee
Requires:	texlive-ocr-b
Requires:	texlive-ocr-b-outline
Requires:	texlive-ogham
Requires:	texlive-oinuit
Requires:	texlive-oldlatin
Requires:	texlive-oldstandard
Requires:	texlive-opensans
Requires:	texlive-orkhun
Requires:	texlive-pacioli
Requires:	texlive-paratype
Requires:	texlive-phaistos
Requires:	texlive-phonetic
Requires:	texlive-pigpen
Requires:	texlive-playfair
Requires:	texlive-poltawski
Requires:	texlive-prodint
Requires:	texlive-punk
Requires:	texlive-punk-latex
Requires:	texlive-punknova
Requires:	texlive-pxtxalfa
Requires:	texlive-quattrocento
Requires:	texlive-raleway
Requires:	texlive-recycle
Requires:	texlive-romande
Requires:	texlive-rsfso
Requires:	texlive-sansmathaccent
Requires:	texlive-sansmathfonts
Requires:	texlive-sauter
Requires:	texlive-sauterfonts
Requires:	texlive-schulschriften
Requires:	texlive-semaphor
Requires:	texlive-skull
Requires:	texlive-sourcecodepro
Requires:	texlive-sourcesanspro
Requires:	texlive-starfont
Requires:	texlive-staves
Requires:	texlive-stix
Requires:	texlive-superiors
Requires:	texlive-tapir
Requires:	texlive-tengwarscript
Requires:	texlive-tfrupee
Requires:	texlive-tpslifonts
Requires:	texlive-trajan
Requires:	texlive-txfontsb
Requires:	texlive-umtypewriter
Requires:	texlive-universa
Requires:	texlive-universalis
Requires:	texlive-urwchancal
Requires:	texlive-venturisadf
Requires:	texlive-wsuipa
Requires:	texlive-xcharter
Requires:	texlive-xits
Requires:	texlive-yfonts
Requires:	texlive-zlmtt
%rename texlive-fontsextra

%description
TeXLive collection-fontsextra package.

#-----------------------------------------------------------------------
%files

#-----------------------------------------------------------------------
%prep
%autosetup -p1 -c

%build

%install
